"""perfume note type

Revision ID: 241d4fe53222
Revises: f192383f0e8f
Create Date: 2024-04-06 18:30:09.793900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241d4fe53222'
down_revision = 'f192383f0e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
