"""perfume note type association

Revision ID: 30ccb2d66002
Revises: 87ff7253af0e
Create Date: 2024-04-06 22:25:45.054972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ccb2d66002'
down_revision = '87ff7253af0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_note_type',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('note_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['note_type_id'], ['note_types.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'note_type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes_note_type')
    # ### end Alembic commands ###
