"""Perfume model fix

Revision ID: 5d1333c82c14
Revises: 7d8a626c129d
Create Date: 2024-04-06 14:26:05.077458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1333c82c14'
down_revision = '7d8a626c129d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfumes', schema=None) as batch_op:
        batch_op.drop_column('test')
        batch_op.drop_column('add')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
