"""perfume note type

Revision ID: 87ff7253af0e
Revises: 241d4fe53222
Create Date: 2024-04-06 18:32:43.191552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ff7253af0e'
down_revision = '241d4fe53222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfume_note', schema=None) as batch_op:
        batch_op.alter_column('note_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfume_note', schema=None) as batch_op:
        batch_op.alter_column('note_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
