"""Added perfume relationship to Notes model

Revision ID: 950ac728dde0
Revises: c8a3aac3ce05
Create Date: 2024-04-06 03:54:33.034840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950ac728dde0'
down_revision = 'c8a3aac3ce05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
