"""perfume note type

Revision ID: f192383f0e8f
Revises: f310fb35e633
Create Date: 2024-04-06 17:14:00.005864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f192383f0e8f'
down_revision = 'f310fb35e633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('perfume_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'note_types', ['note_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfume_note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('note_type_id')

    op.drop_table('note_types')
    # ### end Alembic commands ###
